<?php $params = $this->_params; ?>
<script type="text/javascript">
//<![CDATA[
var options = {
    'key': "<?= $params['public_key'] ?>",
    'amount': "<?= $params['amount'] ?>",
    'description': 'Order for ' + "<?= $params['store_name']?>",
    'currency': "<?= $params['currency_code']?>",
    'sandbox': "<?= $params['sandbox'] ?>",
    'max_installments': "<?= $params['max_installments']?>",
    'onready': "onreadyCallback"
};
EverypayMage.setOptions(options);
EverypayMage.renderAndShow();
//]]>
</script>
<form action="" name="everypay-form" id="everypay-form">
    <div class="button-holder" style="display: none"></div>
</form>
