<script type="text/javascript">
//<![CDATA[
    var head = $$("head")[0];
    var buttonScript = new Element("script", { type: "text/javascript", src: "https://button.everypay.gr/js/button.js" });
    var initButtonScript = new Element("script", { type: "text/javascript", src: "/js/everypay/everypayInitButton.js" })

    head.appendChild(buttonScript);
    head.appendChild(initButtonScript);
//]]>
</script>
<?php $params = $this->_params; ?>
<form action="#" name-"everypay-form" id="everypay-form" method="post">
    <input type="hidden" id="public-key" value="<?= $params['public_key'] ?>" />
    <input type="hidden" id="amount" value="<?= $params['amount'] ?>" />
    <input type="hidden" id="description" value="<?= $params['store_name']?>" />
    <input type="hidden" id="currency" value="<?= $params['currency_code']?>" />
    <input type="hidden" id="sandbox" value="<?= $params['sandbox'] ?>" />
    <div class="button-holder" style="display: none"></div>
</form>
